### ISSUE TITLE
go build failed

### ISSUE THREAD

**Issue by MrWaggel** [gomvn/gomvn#1]
Some of the dependencies have breaking changes.

> 
>  github.com/gofiber/compression
> go/src/github.com/gofiber/compression/main.go:70:13: c.Fasthttp undefined (type *fiber.Ctx has no field or method Fasthttp)
>  github.com/gofiber/logger
> go/src/github.com/gofiber/logger/main.go:140:42: c.Fasthttp undefined (type *fiber.Ctx has no field or method Fasthttp)
> go/src/github.com/gofiber/logger/main.go:142:34: cannot use c.Body() (type []byte) as type string in argument to buf.WriteString
> go/src/github.com/gofiber/logger/main.go:144:46: c.Fasthttp undefined (type *fiber.Ctx has no field or method Fasthttp)
> go/src/github.com/gofiber/logger/main.go:146:46: c.Fasthttp undefined (type *fiber.Ctx has no field or method Fasthttp)
> go/src/github.com/gofiber/logger/main.go:150:29: c.Error undefined (type *fiber.Ctx has no field or method Error)
>  github.com/gomvn/gomvn/internal/service/user
> go/src/github.com/gomvn/gomvn/internal/service/user/create.go:12:16: undefined: gonanoid.ID
> go/src/github.com/gomvn/gomvn/internal/service/user/update_token.go:19:16: undefined: gonanoid.ID

**Comment by lupo112** [comment]
Maybe you are trying to install new version of gofiber (new is `v2`, this repo is using `v1.10`).

Use go modules, there is `go.mod` (and also `go.sum`) file where the exact versions of dependencies are "locked".

If you want to just use this app without any changes, consider to run it with [docker](https://hub.docker.com/r/gomvn/gomvn).
