### ISSUE TITLE
413 Request Entity Too Large from Docker image

### ISSUE THREAD

**Issue by ricoris** [gomvn/gomvn#2]
Hi

Not sure how to fix this error, I downloaded Docker image and it is running. When Maven tries to upload the jar file I get
"413 Request Entity Too Large". I have searche the "net" for a fix, do know a solution?

All extra files is uploaded fine to the repository.

Thanks

**Comment by ricoris** [comment]
adding this to server.go line 22
app.Settings.BodyLimit = 94371840 makes it upload locally.
But will you change the public dockerImage?

**Comment by lupo112** [comment]
Maybe the BodyLimit should be configurable from ENV variables?
I can add it if you need that...
